config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#start'
  #get '/concerts', to: 'welcome#concerts' resources :concerts
  get '/aboutus', to: 'welcome#aboutus'
  get '/participate', to: 'welcome#participate'
  get '/sponsoring', to: 'welcome#sponsoring'
  get '/contact', to: 'welcome#contact'
  # Ressources einfügen:
  # History?
  # Aktuelles / Chorleben
  # concerts
  resources :concerts do
    resources :performers, shallow: true
  end
  
  post '/setGerman', to: 'welcome#german'
  post '/setEnglish', to: 'welcome#english'
  get '/impressum', to: 'welcome#impressum'
  get '/privacyPolicy', to: 'welcome#privacyPolicy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  enum category: [:worship, :concert]
  
  has_many :performers
end

app/models/performer.rb
class Performer < ApplicationRecord
  
  belongs_to :concert
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index 
    @concerts = Concert.all
  end
  
  def new
    
  end
  
  def show
    @concert = Concert.find(params[:id])
  end
  
  def create
    @concert= Concert.new(concert_params)
    
    @concert.save
    redirect_to @concert
  end
  
  private
    def concert_params
      params.require(:concert).permit(:title,:text, :subTitle, :location, :eventDate, :category, :eventTime, :eventDateTitle, :published)
    end
end

app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  
  def index
    
  end
  
  def new
    
  end
  
  def create
    @concert = Concert.find(params[:concert_id])
    @performer = @concert.performers.create(performer_params)
    redirect_to concert_path(@concert)
  end
  
  def show
    
  end
  
  private
  
  def performer_params
    params.require(:performer).permit(:name, :role)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def start
    
  end
  
  def aboutus
    
  end
  
  def participate
    
  end
  
  def sponsoring
    
  end
  
  def contact
    
  end
  
  #legal pages
  def privacyPolicy
    
  end
  
  def impressum
    
  end
  
  #Language setting
  def english
    I18n.locale = :en
    redirect_back fallback_location:  root_url
  end
  
  def german
    I18n.locale = :de
    redirect_back fallback_location:  root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/performers_helper.rb
module PerformersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/concerts/index.html.erb
<div class="container content">

	<h1>Konzerte</h1>

	<% @concerts.each do |concert| %>

	<div class="row tag-box tag-box-v3">
		<div class="col-sm-12">
			<div class="row">
				<div class="col-md-10 col-sm-12">
					<h2><%= concert.title %></h2>
					<h3><%= concert.subTitle %></h3>
				</div>
				<div class="col-md-2 col-sm-12">
					<%= concert.eventDate %>
					<br/>
					<%= concert.eventTime %>
					<br/>
					<%= concert.eventDateTitle %>
				</div>
			</div>
		</div>
		<div class="col-md-6 col-sm-12">
			<%= concert.text %>
		</div>
		<div class="col-md-6 col-sm-12">
			Keine Mitwirkenden genannt
			<% concert.performers.each do |performer| %>
			blub
			<% end %>
		</div>
		<div class="col-sm-12">
			<%= concert.location %>, <%= concert.category %>, <%= concert.published %>
		</div>
	</div>
	<%= link_to 'Show', concert_path(concert) %>
	<% end %>
</div>

app/views/concerts/new.html.erb
<div class="container content">
<h1>New Concert</h1>


<%= form_for :concert, url: concerts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :subTitle %><br>
    <%= f.text_field :subTitle %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  
  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>
 <p>
    <%= f.label :category %><br>
    <%= f.select :category, Concert.categories.keys %>
  </p>
  <p>
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </p>
  <p>
    <%= f.label :eventDateTitle %><br>
    <%= f.text_field  :eventDateTitle %>
  </p>
  <p>
    <%= f.label :eventDate %><br>
    <%= f.date_field :eventDate %>
  </p>
  <p>
    <%= f.label :eventTime %><br>
    <%= f.time_field :eventTime %>
  </p>
  <p>
    <%= f.submit "Create", :class => 'btn-u' %>
  </p>
<% end %>
</div>

app/views/concerts/show.html.erb
<div class="container content">
	<div class="row tag-box tag-box-v3">
		<div class="col-sm-12">
			<div class="row">
				<div class="col-md-10 col-sm-12">
					<h2><%= @concert.title %> <small><%= @concert.subTitle %></small></h2>

				</div>
				<div class="col-md-2 col-sm-12">
					<%= @concert.eventDate.strftime("%-d. %B %Y") %>
					<br/>
					<%= @concert.eventTime.strftime("%R") %> Uhr
					<br/>
					<%= @concert.eventDateTitle %>
				</div>
			</div>
			<hr class="no-margin margin-bottom-10 margin-top-10"/>
		</div>
		<div class="col-md-6 col-sm-12">
			<%= @concert.text %>
		</div>
		<div class="col-md-6 col-sm-12">
			<h4><%= t("concerts.show.heading.performers")%></h4>
			<% @concert.performers.each do |performer| %>
			<div class="testimonials testimonials-v1">
				<div class="testimonial-info">
					<%= image_tag("user.jpg", class: "rounded-x")%>
					<span class="testimonial-author"><%= performer.name %> <em><%= performer.role %></em></span>
				</div>
			</div>
			<hr class="margin-bottom-10">
			<% end %>
			<% if @concert.performers.count <= 0 %>
			<p>
				<%= t("concerts.show.noPerformers")%>
			</p>
			<% end %>

			<%= link_to t("concerts.show.addPerformer")%>
		</div>
		<div class="col-sm-12">
			<hr/>
			<ul class="list-inline">
				<li>
					<i class="fa fa-map-marker color-green"></i> <%= @concert.location %>
				</li>
				<li>
					<i class="fa fa-tags color-green"></i> <%= @concert.category %>
				</li>
				<li>
					<i class="fa fa-bullhorn color-green"></i>
					<em> <% if @concert.published? %>
					<%= t("concerts.show.published")%>
					<% else %>
					<%= t("concerts.show.draft")%>
					<% end %></em>
				</li>
			</ul>
		</div>
	</div>

</div><!--/container-->

app/views/layouts/_footer.html.erb
<!--=== Footer v1 ===-->
		<footer id="footer-v1" class="footer-v1">
			<div class="footer">
				<div class="container">
					<div class="row">
						<!-- About -->
						<div class="col-md-3 md-margin-bottom-40">
							<!-- <a href="index.html"><img id="logo-footer" class="footer-logo" src="assets/img/logo2-default.png" alt=""></a> -->
							<%= link_to image_tag("pictures/annenchor_logo_mit_schrift_klein"), root_path, :id => "logo-footer"%>
							<p>About Unify dolor sit amet, consectetur adipiscing elit. Maecenas eget nisl id libero tincidunt sodales.</p>
							<p>Duis eleifend fermentum ante ut aliquam. Cras mi risus, dignissim sed adipiscing ut, placerat non arcu.</p>
						</div>
						<!-- End About -->

						<!-- Latest -->
						<div class="col-md-3 md-margin-bottom-40">
							<div class="posts">
								<div class="headline"><h2><%= (t "footer.lastTidings") %></h2></div>
								<ul class="list-unstyled latest-list">
									<li>
										<a href="#">Incredible content</a>
										<small>May 8, 2014</small>
									</li>
									<li>
										<a href="#">Best shoots</a>
										<small>June 23, 2014</small>
									</li>
									<li>
										<a href="#">New Terms and Conditions</a>
										<small>September 15, 2014</small>
									</li>
								</ul>
							</div>
						</div>
						<!-- End Latest -->

						<!-- Link List -->
						<div class="col-md-3 md-margin-bottom-40">
							<div class="headline"><h2><%= (t "footer.navigation") %></h2></div>
							<ul class="list-unstyled link-list">
								<li><%= link_to (t "navbar.start"), root_path%><i class="fa fa-angle-right"></i></li>
								<li><%= link_to (t "navbar.concerts"), concerts_path%><i class="fa fa-angle-right"></i></li>
								<li><%= link_to (t "navbar.aboutus"), aboutus_path%><i class="fa fa-angle-right"></i></li>
								<li><%= link_to (t "navbar.tidings") %><i class="fa fa-angle-right"></i></li>
								<li><%= link_to (t "navbar.participate"), participate_path%><i class="fa fa-angle-right"></i></li>
								<li><%= link_to (t "navbar.sponsoring"), sponsoring_path%><i class="fa fa-angle-right"></i></li>
								<li><%= link_to (t "navbar.contact"), contact_path%><i class="fa fa-angle-right"></i></li>
							</ul>
						</div>
						<!-- End Link List -->

						<!-- Address -->
						<div class="col-md-3 map-img md-margin-bottom-40">
							<div class="headline"><h2><%= (t "footer.contactus.heading") %></h2></div>
							<address class="md-margin-bottom-40">
								Dingbängerweg 61 <br />
								48163 Münster <br />
								<%= (t "footer.contactus.phone")%>: <a href="tel:+49251717077" class="">+49 251 71 70 77</a><br />
								<%= (t "footer.contactus.fax")%>: <a href="" class="">+49 251 XXX</a><br />
								<%= (t "footer.contactus.email")%>: <a href="mailto:info@anybiz.com" class="">info@anybiz.com</a>
							</address>
						</div>
						<!-- End Address -->
					</div>
				</div>
			</div><!--/footer-->

			<div class="copyright">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<p>
								<%= Time.now.year %> &copy; <%= (t "footer.copyright") %>
								<%= link_to (t "footer.privacypolicy"), privacyPolicy_path %> | <%= link_to (t "footer.impressum"), impressum_path %>
							</p>
						</div>

						<!-- Social Links -->
						<div class="col-md-6">
							<ul class="footer-socials list-inline">
								<li>
									<a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
										<i class="fa fa-facebook"></i>
									</a>
								</li>
								<li>
									<a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype">
										<i class="fa fa-skype"></i>
									</a>
								</li>
								<li>
									<a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google Plus">
										<i class="fa fa-google-plus"></i>
									</a>
								</li>
								<li>
									<a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Linkedin">
										<i class="fa fa-linkedin"></i>
									</a>
								</li>
								<li>
									<a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Pinterest">
										<i class="fa fa-pinterest"></i>
									</a>
								</li>
								<li>
									<a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
										<i class="fa fa-twitter"></i>
									</a>
								</li>
							</ul>
						</div>
						<!-- End Social Links -->
					</div>
				</div>
			</div><!--/copyright-->
		</footer>
		<!--=== End Footer v1 ===-->

app/views/layouts/_navbar.html.erb
<!--=== Header v6 ===-->
<header class="header-v6 header-classic-dark header-dark-dropdown header-sticky">
	<!-- <header class="header-v6 header-dark-transparent header-dark-dropdown header-sticky"> -->
	<!-- Navbar -->
	<div class="navbar mega-menu" role="navigation">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="menu-container">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

				<!-- Navbar Brand -->
				<!-- <div class="navbar-brand">
				<%= link_to image_tag("pictures/annenchor_logo_einzeln_klein", :class => "shrink-logo"), root_path %>
				</div> -->
				<div class="navbar-brand">
					<%= link_to image_tag("pictures/annenchor_logo_einzeln_klein", :class => "default-logo"), root_path %>
				</div>
				<!-- End Navbar Brand -->

				<!-- Header Inner Right -->
				<div class="header-inner-right">
					<ul class="menu-icons-list">
						<li class="menu-icons">
							<i class="menu-icons-style search search-close search-btn fa fa-search"></i>
							<div class="search-open">
								<input type="text" class="animated fadeIn form-control" placeholder="Suchen ...">
							</div>
						</li>
						<li class="menu-icons">
							<a><i class="menu-icons-style fa fa-globe"></i></a>
						</li>
					</ul>
				</div>
				<!-- End Header Inner Right -->
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse navbar-responsive-collapse">
				<div class="menu-container">
					<ul class="nav navbar-nav">
						<li class=<%= current_page?(root_path) ? "active" : "" %> >
							<%= link_to (t "navbar.start"), root_path%>
						</li>
						<li class=<%= current_page?(concerts_path) ? "active" : "" %>>
							<%= link_to (t "navbar.concerts"), concerts_path%>
						</li>
						<li class=<%= current_page?(aboutus_path) ? "active dropdown" : "dropdown" %>>
							<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"> <%= (t "navbar.aboutus") %> </a>
							<ul class="dropdown-menu">
								<li>
									<%= link_to (t "navbar.aboutus"), aboutus_path%>
								</li>
								<li>
									<%= link_to (t "navbar.tidings") %>
								</li>
							</ul>
						</li>
						<li class=<%= current_page?(participate_path) ? "active" : "" %>>
							<%= link_to (t "navbar.participate"), participate_path%>
						</li>
						<li class=<%= current_page?(sponsoring_path) ? "active" : "" %>>
							<%= link_to (t "navbar.sponsoring"), sponsoring_path%>
						</li>
						<li class=<%= current_page?(contact_path) ? "active" : "" %>>
							<%= link_to (t "navbar.contact"), contact_path%>
						</li>
					</ul>
				</div>
			</div><!--/navbar-collapse-->
		</div>
	</div>
	<!-- End Navbar -->
</header>
<!--=== End Header v6 ===-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
	<!--<![endif]-->
	<head>
		<title>Annenchor</title>
		<%= csrf_meta_tags %>

		<!-- Favicon -->
		<link rel="shortcut icon" href="favicon.ico">

		<!-- Web Fonts -->
		<link rel="shortcut" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:400,300,600&subset=cyrillic,latin">

		<!-- CSS Global Compulsory -->
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

		<!-- Font Awesome -->
		<script src="https://use.fontawesome.com/f1e6ff008c.js"></script>

	</head>

	<body class="header-fixed header-fixed-space <%= controller_name + "_" + action_name %>">
		<div class="wrapper">
			<%= render :partial => 'layouts/navbar' %>
			<!--=== Content Part  ===-->
			<%= yield %>
			<!--=== End Content Part  ===-->

			<%= render :partial => 'layouts/footer' %>

		</div>
	</body>
	<script src="//maps.googleapis.com/maps/api/js?key=AIzaSyBzUlKXl-Y6EpXR8lWTrggld65fv1E9HtE&callback=initMap" async defer></script>
	
</html>

app/views/welcome/aboutus.html.erb
<div class="container content"></div>

app/views/welcome/contact.html.erb
<!-- Google Map -->
<div id="map" class="map"></div>
<!-- End Google Map -->

<!--=== Content Part ===-->
<div class="container content">
	<div class="row margin-bottom-30">
		<div class="col-md-9 mb-margin-bottom-30">
			<div class="headline">
				<h2><%= t("contact.headings.main")%></h2>
			</div>
			<p>
				<%= t("contact.text")%>
			</p>
			<br />

			<form action="assets/php/sky-forms-pro/demo-contacts-process.php" method="post" id="sky-form3" class="sky-form contact-style">
				<fieldset class="no-padding">
					<label><%= t("contact.form.labels.name")%> <span class="color-red">*</span></label>
					<div class="row sky-space-20">
						<div class="col-md-7 col-md-offset-0">
							<div>
								<input type="text" name="name" id="name" class="form-control">
							</div>
						</div>
					</div>

					<label><%= t("contact.form.labels.email")%> <span class="color-red">*</span></label>
					<div class="row sky-space-20">
						<div class="col-md-7 col-md-offset-0">
							<div>
								<input type="text" name="email" id="email" class="form-control">
							</div>
						</div>
					</div>

					<label><%= t("contact.form.labels.message")%> <span class="color-red">*</span></label>
					<div class="row sky-space-20">
						<div class="col-md-11 col-md-offset-0">
							<div>
								<textarea rows="8" name="message" id="message" class="form-control"></textarea>
							</div>
						</div>
					</div>

					<p>
						<button type="submit" class="btn-u">
							<%= t("contact.form.buttons.send")%>
						</button>
					</p>
				</fieldset>

				<div class="message">
					<i class="rounded-x fa fa-check"></i>
					<p>
						<%= t("contact.form.alerts.success")%>
					</p>
				</div>
			</form>
		</div><!--/col-md-9-->

		<div class="col-md-3">
			<!-- Contacts -->
			<div class="headline">
				<h2><%= t("contact.headings.contactdata")%></h2>
			</div>
			<ul class="list-unstyled who margin-bottom-30">
				<li>
					<a href="#"><i class="fa fa-home"></i>Dingbängerweg 61, 48163 Münster</a>
				</li>
				<li>
					<a href="mailto:info@annenchor.de"><i class="fa fa-envelope"></i>info@annenchor.de</a>
				</li>
				<li>
					<a href="tel:+49251717077" class=""><i class="fa fa-phone"></i> +49 251 71 70 77</a>
				</li>
				<li>
					<a href="http://annenchor.de"><i class="fa fa-globe"></i>http://annenchor.de</a>
				</li>
			</ul>

			<!-- Business Hours -->
			<div class="headline">
				<h2><%= t("contact.headings.businesshours")%></h2>
			</div>
			<ul class="list-unstyled margin-bottom-30">
				<li>
					<strong>Monday-Friday:</strong> 10am to 8pm
				</li>
				<li>
					<strong>Saturday:</strong> 11am to 3pm
				</li>
				<li>
					<strong>Sunday:</strong> Closed
				</li>
			</ul>

			<!-- Why we are? -->
			<div class="headline">
				<h2><%= t("contact.headings.practice")%></h2>
			</div>
			<p>
				Geprobt wird im Gruppenraum des Pfarrzentrums der St. Anna-Kirche am Dingbängerweg
			</p>
			<ul class="list-unstyled">
				<li>
					<strong><%= t("contact.practice.thursday")%>:</strong>  <%= t("contact.practice.thursdayhours")%>
				</li>
			
			</ul>
		</div><!--/col-md-3-->
	</div><!--/row-->
</div>

app/views/welcome/participate.html.erb
<div class="container content">
	</div>

app/views/welcome/sponsoring.html.erb
<div class="container content">
	</div>